### ISSUE TITLE
The game crashes randomly

### ISSUE THREAD

**Issue by mshwf** [AndreiMisiukevich/RawRows#2]
I know you fired and forgot that game :D,
but I'm playing it almost every day for a month or so.
and it happens a lot while I play, that I move tiles fast, the game crashes!
After a little debugging, found [the code](https://github.com/AndreiMisiukevich/RawRows/blob/master/FifteenInRow.Android/AudioService.cs#L26
) that causes this:
```
player.Prepared += (s, e) =>
     {
         player.Start();
    };
```
after replacing it with this:

```
player.Prepared += (s, e) =>
     {
         ((MediaPlayer)s).Start();
    };
```
it stopped crashing (I'm currently using my debug-version for a week)

**Comment by AndreiMisiukevich** [comment]
@mshwf Hi :) Thanks for your report.
Honestly speaking, I don't see the difference in that code. the player already has MediaPlayer type.
I think it might be something different. Maybe some problem with the main thread.

you try to invoke player.Start(); in main thread and check if it crashes.

**Comment by mshwf** [comment]
Actually, I didn't spend much time debugging, I only wanted to play :D 
once I got it stable in my hands I concluded that this is the fix.
will try your suggested solution the next time I open the project. 👍🏼

**Comment by AndreiMisiukevich** [comment]
Ohhh, okay, I see the difference now, interesting.
Would you like to make a PR?)

**Comment by mshwf** [comment]
glad to contribute :)

**Comment by mshwf** [comment]
> Ohhh, okay, I see the difference now, interesting. Would you like to make a PR?)

Now, after my PR has been merged, I'm happy I won't need to debug the bug to understand the real issue :D
could you share your conclusion? :)
I'm still not sure why it fixed it!
especially it happens on rapidly successive calls.
what is the thread doing in between, that it doesn't finish?

**Comment by AndreiMisiukevich** [comment]
@mshwf honestly speaking, I have no idea...) that is so weird
